### ISSUE TITLE
TypeError: can't convert CUDA tensor to numpy.

### ISSUE THREAD

**Issue by alessandrostranieri** [dicarlolab/CORnet#11]
Hello, 

I tried to make a simple test with one image. Following the instruction I run:

```
python run.py test --model S --data_path images --output_path features --ngpus=1
```

The script is failing with on both windows and linux:

```
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first
```

Here's my conda environment:

```
python 3.7.6
pandas 1.0.1
pytorch 1.4.0
numpy 1.18.1
```

I will be investigating on a solution for this, but I was wondering whether you've already some insight on the problem. Have the modules been tested with a more recent version of PyTorch? Thanks!

**Comment by mschrimpf** [comment]
Hi @alessandrostranieri, could you post the full stack trace so we can see where the error is originating from? Is it in https://github.com/dicarlolab/CORnet/blob/master/run.py#L203? 
We usually just run `test` on cpu, but if it's that line you could probably fix it quickly by adding the suggested `.cpu()`

**Comment by alessandrostranieri** [comment]
Hello, thanks for the help!

The error goes away if I change the line you mentioned to:

```python
 _model_feats.append(np.reshape(output.cpu(), (len(output), -1)).numpy())
```
I'll close the issue, but I am posting some extra info: it might be useful.

The stack trace was:

```
Traceback (most recent call last):
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
TypeError: reshape() got an unexpected keyword argument 'order'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/deral/University/Thesis/CORnet/run.py", line 350, in <module>
    fire.Fire(command=FIRE_FLAGS)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:/Users/deral/University/Thesis/CORnet/run.py", line 226, in test
    model(im)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\torch\nn\modules\module.py", line 534, in __call__
    hook_result = hook(self, input, result)
  File "C:/Users/deral/University/Thesis/CORnet/run.py", line 203, in _store_feats
    _model_feats.append(np.reshape(output, (len(output), -1)).numpy())
  File "<__array_function__ internals>", line 6, in reshape
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\numpy\core\fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\numpy\core\fromnumeric.py", line 70, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\numpy\core\fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\deral\Anaconda3\envs\PyThesis\lib\site-packages\torch\tensor.py", line 486, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Process finished with exit code 1
```

When I was investigating with the debugger, I noticed that the object `bound` in `fromnumeric.py:56` of numpy was _bound_ to the function `torch.reshape` of pytorch, but called with the `order` keyword of `numpy.reshape`. This seems to be the cause of the original exception. Unfortunately I am not familiar enough with either library to understand further, but I hope it can be helpful.

**Comment by alessandrostranieri** [comment]
By the way, you mentioned that tests are typically on CPU, which was also my first attempt. Unfortunately I am failing at that too, so I am going to open another issue sorry :)

**Comment by qbilius** [comment]
I pushed the commit similar to what @mschrimpf proposed. This fixes the problem for me when running on a GPU (in Linux).
